<div id="textile-quickref">
    <h3>Phrase modifiers</h3>
    <ul>
        <li><em>_emphasis_</em></li>
        <li><strong>*strong*</strong></li>
        <li><cite>??citation??</cite></li>
        <li>-<del>deleted text</del>-</li>
        <li>+<ins>inserted text</ins>+</li>
        <li>^<sup>superscript</sup>^</li>
        <li>~<sub>subscript</sub>~</li>
        <li><span>%span%</span></li>
<!--
        <li><code>@code@</code></li>
-->
    </ul>
    <h3>Block modifiers</h3>
    <ul>
        <li><strong>h<em>n</em>.</strong> heading</li>
        <li><strong>bq.</strong> Blockquote</li>
        <li><strong>fn<em>n</em>.</strong> Footnote</li>
        <li><strong>p.</strong> Paragraph</li>
        <li><strong>bc.</strong> Block code</li>
        <li><strong>pre.</strong> Pre-formatted</li>
        <li><strong>#</strong> Numeric list</li>
        <li><strong>*</strong> Bulleted list</li>
    </ul>
    <h3>Links</h3>
    <ul>
        <li>"linktext":http://…</li>
    </ul>
    <h3>Punctuation</h3>
    <ul>
        <li><strong>"quotes"</strong> → “quotes”</li>
        <li><strong>'quotes'</strong> → ‘quotes’</li>
        <li><strong>it's</strong> → it’s</li>
        <li><strong>em -- dash</strong> → em — dash</li>
        <li><strong>en - dash</strong> → en – dash</li>
        <li><strong>2 x 4</strong> → 2 × 4</li>
        <li><strong>foo(tm)</strong> → foo™</li>
        <li><strong>foo(r)</strong> → foo®</li>
        <li><strong>foo(c)</strong> → foo©</li>
    </ul>
    <h3>Attributes</h3>
    <ul>
        <li>(class)</li>
        <li>(#id)</li>
        <li>{style}</li>
        <li>[language]</li>
    </ul>
    <h3>Images</h3>
    <ul>
        <li>!imageurl!</li>
        <li>!imageurl!:http://…</li>
    </ul>
    <h3>Acronyms</h3>
    <ul>
        <li>ABC(Always Be Closing)</li>
    </ul>
    <h3>Footnotes</h3>
    <ul>
        <li>See foo[<em>1</em>].</li>
        <li>fn1. Foo.</li>
    </ul>
</div>