<?= $this->doctype() ?>
<html>
<head>
<?= $this->headTitle() ?>
<?= $this->headMeta() ?>
<?= $this->headLink()
        ->appendStylesheet($this->baseUrl('/css/reset-screen.css'), 'screen')
?>
<?= $this->headScript() ?>
</head>
<body>
<h1>Postr</h1>
<div id="content">
<?= $this->layout()->content; ?>
</div>
<div id="header">
<?= $this->render('header.phtml') ?>
</div>
<div id="footer">
<?= $this->render('footer.phtml') ?>
</div>
</body>
</html>
